stages:
  - build
  - push
  - deploy  

image: docker:latest
services:
  - docker:dind

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  REPOSITORY: "danilodesousa"

cache:
  paths:
    - .m2/repository

clients:install:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - cd clients; mvn clean install -U
  only:
    - master
  artifacts:
    paths:
     - clients/target/*.jar
    expire_in: 1 week
  
purchase:install:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - cd purchase; mvn clean install -U
  only:
    - master
  artifacts:
    paths:
     - purchase/target/*.jar
    expire_in: 1 week

push:clients:
  stage: push
  script:
    - ls
    - cd clients
    - ls
    - docker build -t $REPOSITORY/clients:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD "docker.io"
    - docker push $REPOSITORY/clients:latest
  only:
    - master
  artifacts:
    paths:
     - clients/target/*.jar
    expire_in: 1 week

push:purchase:
  stage: push
  script:
    - ls
    - cd purchase
    - ls
    - docker build -t $REPOSITORY/purchase:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD "docker.io"
    - docker push $REPOSITORY/purchase:latest
  only:
    - master
  artifacts:
    paths:
     - purchase/target/*.jar
    expire_in: 1 week

k8s-create-cluster:
  image: google/cloud-sdk
  stage: deploy
  script:
    - gcloud auth activate-service-account --key-file key.json
    - gcloud container clusters create master --zone us-central1-a --project clients --enable-autoscaling --max-nodes=3 --min-nodes=1 --machine-type=n1-standard-2
  only:
    - master
  when: manual
  allow_failure: true

k8s-deploy-production:
  stage: deploy
  image: google/cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file key.json
    - gcloud container clusters get-credentials master --zone us-central1-a --project clients
    - kubectl --namespace=default apply -f clients-deployment.yaml
    - kubectl --namespace=default apply -f purchase-deployment.yaml
  only:
    - master
  allow_failure: true


