image: maven:3.3.9-jdk-8


variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  IMAGE: "danilodesousa/clients"


cache:
  paths:
    - .m2/repository

deploy:install:
  stage: build
  script:
    - cd clients; mvn clean install -U
  only:
    - master

push:docker-hub:
  stage: push
  script:
    - docker build -t $IMAGE:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD "docker.io"
    - docker push $IMAGE:latest
