apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: clients
spec:
  selector:
    matchLabels:
      app: clients
      tier: backend
  replicas: 3
  
  template:
    metadata:
      labels:
        app: clients
        tier: backend
    spec:
      containers:
      - name: clients
        image: danilodesousa/clients:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          #value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          value: env
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: clients
  labels:
    app: clients
    tier: backend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: clients
    tier: backend

