spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/client
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
      
